cargo-features = ["edition2024"]

[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.86"
include_dir = { version = "0.7.4", features = ["nightly"] }
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-rustls", "postgres" ] }
tokio = { version = "1.39.2", features = ["full"] }
tracing = "0.1.40"
