-- Add migration script here

CREATE EXTENSION moddatetime;

-- Schemas

CREATE TABLE dp_schemas (
    schema_id VARCHAR(255) PRIMARY KEY,
    picture TEXT,
    description TEXT NOT NULL DEFAULT '',

    initial_sql TEXT NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TRIGGER dp_schemas_moddatetime
BEFORE UPDATE ON dp_schemas
FOR EACH ROW
EXECUTE PROCEDURE MODDATETIME(updated_at);

CREATE TYPE dp_difficulty AS ENUM ('easy', 'medium', 'hard');

CREATE TABLE dp_questions (
    question_id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    -- schema_id turns to NULL if the schema is deleted
    schema_id VARCHAR(255) REFERENCES dp_schemas ON DELETE SET NULL,

    type VARCHAR(255) NOT NULL,
    difficulty DP_DIFFICULTY NOT NULL,

    title VARCHAR(512) NOT NULL,
    description TEXT NOT NULL DEFAULT '',

    answer TEXT NOT NULL,
    solution_video TEXT,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TRIGGER dp_questions_moddatetime
BEFORE UPDATE ON dp_questions
FOR EACH ROW
EXECUTE PROCEDURE MODDATETIME(updated_at);

-- Users

CREATE TABLE dp_groups (
    group_id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TRIGGER dp_groups_moddatetime
BEFORE UPDATE ON dp_groups
FOR EACH ROW
EXECUTE PROCEDURE MODDATETIME(updated_at);

CREATE TABLE dp_users (
    user_id VARCHAR(255) PRIMARY KEY NOT NULL,
    group_id BIGINT REFERENCES dp_groups ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TRIGGER dp_users_moddatetime
BEFORE UPDATE ON dp_users
FOR EACH ROW
EXECUTE PROCEDURE MODDATETIME(updated_at);
